// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvp5LNrg2AMUGvz8diBqIfE0hwxUkEuNk',
    appId: '1:636124913916:web:210aff79a5a9a770747779',
    messagingSenderId: '636124913916',
    projectId: 'hostelhop-1f47e',
    authDomain: 'hostelhop-1f47e.firebaseapp.com',
    storageBucket: 'hostelhop-1f47e.firebasestorage.app',
    measurementId: 'G-VDQTNYLVRH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeeJNlzgn1xhBL-vhoUW3gWJsrFDERX2s',
    appId: '1:636124913916:android:855c4dc3b26249fc747779',
    messagingSenderId: '636124913916',
    projectId: 'hostelhop-1f47e',
    storageBucket: 'hostelhop-1f47e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqcZ6HI5verWP3eQx2O1zWc3xBnBAPTGs',
    appId: '1:636124913916:ios:2fe47b678cf89930747779',
    messagingSenderId: '636124913916',
    projectId: 'hostelhop-1f47e',
    storageBucket: 'hostelhop-1f47e.firebasestorage.app',
    iosBundleId: 'com.hostel.hop.hostelhop',
  );
}
